### ISSUE TITLE
putch callback

### ISSUE THREAD

**Issue by fizzyade** [AndreRenaud/EmbeddedCLI#27] opened 2023-10-15 19:49 UTC
Hi,

It would be advantageous for the callback for putch to have a additional parameter that indicates whether the character is the last byte in the transmission.

As an example, the usage case where the transport is over USB, single byte transfers are an *expensive* operation.  With an additional parameter that either tells us that this is the last byte allows flushing to be handled in the call-back directly without needing other solutions or the parameter saying "you can flush now" would make better use of the USB bus.

**Comment by AndreRenaud** [comment] 2023-10-15 21:52
Hi,
That seems like a pretty reasonable/easy requirement. Can you tell me if https://github.com/AndreRenaud/EmbeddedCLI/pull/28 works how you'd expect?

**Comment by fizzyade** [comment] 2023-10-15 23:46
Hi! It's early in the morning here so I will take a look later today, I was going to create a PR myself!

I'll let you know after I pull this in, many thanks for a fast reply!

**Comment by fizzyade** [comment] 2023-10-16 16:27
> Hi,
> That seems like a pretty reasonable/easy requirement. Can you tell me if #28 works how you'd expect?

Yes, I just tried it and that is indeed working! :)

However...I'm seeing an issue when going through the history, the issue occurs no matter what terminal I am using, basically it I type a few commands and then use up and down you can see that once I just the earliest entry and start going the other way, the history goes wrong and starts deleting part of prompt.

Now, my prompt does have ANSI escape sequences in it to colorise it, so I don't know if that's contributing to it.  I need to take a look later on and see if I can see why this is happening, I have attached a GIF showing it happening and hopefully GitHub will show it.

![History Prompt Eating](https://github.com/AndreRenaud/EmbeddedCLI/assets/55795671/4cd6f4b6-ac2b-4334-9900-588f53a3b653)

**Comment by AndreRenaud** [comment] 2023-10-16 17:48
I've just done a check in `main`, and I can still replicate this. So I don't think this is a result of this change. It looks like going up is ok, but when you go down the cursor ends up at the beginning of the line, not the end, then the next time you hit down it backspaces too far.

I'll have a look as well - please let me know if you find the cause.

**Comment by fizzyade** [comment] 2023-10-16 17:54
Ok cool.

I will have a look a bit later after we’ve eaten!

Other than this it appears to be working great for me now, many thanks for the quick implementation of is_last!

Adrian

**Comment by fizzyade** [comment] 2023-10-16 18:29
> Ah, I think I might have spotted it. This stuff is a bit hairy, and I realise now that this code if pretty poorly documented. The upshot is that if you reach the end of the history, it doesn't reset the buffer to empty, which means it backspaces over characters that it's not drawing.
> 
> 
> 
> Can you try this one? I'll merge the `is_last` stuff
> 
> https://github.com/AndreRenaud/EmbeddedCLI/pull/29

Thanks! I will check in a bit, going to have a good look at the code and see if I can add anything I think is missing!

**Comment by fizzyade** [comment] 2023-10-16 19:34
> Ah, I think I might have spotted it. This stuff is a bit hairy, and I realise now that this code if pretty poorly documented. The upshot is that if you reach the end of the history, it doesn't reset the buffer to empty, which means it backspaces over characters that it's not drawing.
> 
> Can you try this one? I'll merge the `is_last` stuff #29

Ok, this has resolved the issue with the dissappearing prompt, however, moving through the history seems a bit weird, it seems to wrap around when you press up, but down behaves as I would expect (stopping at the end), this means that because it wraps going up, you can go past the start but then can't go back down since you get stuck, so you have to go all the way back around to the command you want going up.

I realise that I probably haven't explained that very well.

The behaviour I would expect is no matter which direction you go through the history that either the start or the end of the history should be a hard stop.

I'm going to have a look at the code and get acquainted with it!

I really appreciate your responses here, I know that writing open-source software can sometimes be a thankless task!

**Comment by AndreRenaud** [comment] 2023-10-16 19:43
Yes, I'd seen that, but hadn't really worried about it too much. It's because I'm resetting a bunch of things when you reach the beginning of the history list, which includes where you're up to in the list. I've just pushed a minor tweak that restores that value (slight hack, ah well).

Want to try it now (on the https://github.com/AndreRenaud/EmbeddedCLI/pull/29 branch)?

**Comment by fizzyade** [comment] 2023-10-16 19:50
> Yes, I'd seen that, but hadn't really worried about it too much. It's because I'm resetting a bunch of things when you reach the beginning of the history list, which includes where you're up to in the list. I've just pushed a minor tweak that restores that value (slight hack, ah well).
> 
> Want to try it now (on the #29 branch)?

Perfect, working as expected now! :)

**Comment by AndreRenaud** [comment] 2023-10-16 19:53
Great!

I'll close this issue, since it relates to things we've resolved. Let me know if you have any other problems.

Thanks for the report.

**Closed by AndreRenaud** 2023-10-16 19:53 UTC

**Comment by fizzyade** [comment] 2023-10-16 19:55
> Great!
> 
> I'll close this issue, since it relates to things we've resolved. Let me know if you have any other problems.
> 
> Thanks for the report.

You're welcome, many thanks for taking on board my suggestion and then fixing the subsequent issues I discovered!

Cool little library!
